{% set name = "amazon-codewhisperer-jupyterlab-ext" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-codewhisperer-jupyterlab-ext-{{ version }}.tar.gz
  sha256: ff19ee8f4901f6306b14b7313d4669b289aee3acda3831d6b44080e07327b5df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.10,<1.dev0,<2
    - jupyterlab >=3.1,<4.dev0
    - pip
  run:
    - python >=3.6
    - boto3
    - botocore
    - jupyterlab >=3.1,<4.dev0

test:
  imports:
    - amazon_codewhisperer_jupyterlab_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/codewhisperer/
  summary: Amazon CodeWhisperer for JupyterLab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kumarnzt
    - dhanainme
    - andrewyuq
